"""
Django settings for rushyrealm project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ddodriy*xyjjd4tq&5%xb#x5v2_b7o%s#^*15fphi$**0(&x)y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # MAIN APPS
    'app_order',
    'app_product',
    'app_confirmation',

    # 3RD-PARTY APPS
    'ckeditor',
    'crispy_forms',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rushyrealm.urls'

SITE_ID = 1

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rushyrealm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

########### ZEA CUSTOM SETTING ###########

# CKEDITOR SETTING
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['codesnippet', 'codesnippetgeshi'],
            ['RemoveFormat', 'Source']
        ],
           'height': 400,
           'width': 700,
    }
}

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

# CRISP_FORMS_SETTINGS
CRISPY_CLASS_CONVERTERS = {'textinput': "form-control rushy-input", 'urlinput': "form-control rushy-input", 'numberinput': "form-control rushy-input", 'emailinput': "form-control rushy-input", 'dateinput': "form-control rushy-input", 'textarea': "form-control rushy-input", 'select': "form-control rushy-input" }

# auth and allauth settings
LOGIN_URL                               = '/order/login/'
LOGIN_REDIRECT_URL                      = '/'
LOGOUT_REDIRECT_URL                     = '/'
ACCOUNT_LOGIN_REDIRECT_URL              = '/'
ACCOUNT_LOGOUT_REDIRECT_URL             = '/'
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS   = True
SOCIALACCOUNT_QUERY_EMAIL               = True
SOCIALACCOUNT_AUTO_SIGNUP               = True
SOCIALACCOUNT_EMAIL_VERIFICATION        = False
ACCOUNT_LOGOUT_ON_GET                   = True
SOCIALACCOUNT_PROVIDERS                 = \
    {'facebook':
       {'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': [
            'id',
            'email',
            'name',],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.6'}}

# EMAIL SERVER SETTING
# Server API token: https://account.postmarkapp.com/servers/1813802/credentials
# postmarkapp email backends
EMAIL_USE_TLS        = True
EMAIL_HOST           = 'smtp.postmarkapp.com'
EMAIL_PORT           = 587
POSTMARK_API_KEY     = '6b565225-5ad3-4312-b85c-d930e46d53ef'
POSTMARK_SENDER      = 'hello@rushyrealm.com'
EMAIL_HOST_USER      = POSTMARK_SENDER
DEFAULT_FROM_EMAIL   = POSTMARK_SENDER
POSTMARK_TEST_MODE   = False
POSTMARK_TRACK_OPENS = False
EMAIL_BACKEND        = 'postmark.django_backend.EmailBackend'
OUR_COMPANY_EMAILS   = ['cahyosumirat93@gmail.com', 'alzea.arafat@gmail.com']

# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'sandy.raharjaa@gmail.com'
# EMAIL_HOST_PASSWORD = 'Nallaismystar!!!'
# EMAIL_PORT = 587


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE'    : 'django.db.backends.mysql',
        'NAME'      : 'startup_rushyrealmv2DB',
        'USER'      : 'root',
        'PASSWORD'  : 'root',
        'HOST'      : 'localhost',
        'PORT'      : '',
    }
}

########### END OF LINES ###########

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    '/home/zea/Startup/rushyrealm_v2_env/rushyrealm/static',
)

STATIC_URL      = '/static/'
# STATIC_ROOT   = '/home/zea/Startup/rushyrealm_v2_env/rushyrealm/static'

MEDIA_URL   = '/media/'
MEDIA_ROOT  = '/home/zea/Startup/rushyrealm_v2_env/rushyrealm/media'

CKEDITOR_UPLOAD_PATH    = 'media/uploads/'
CKEDITOR_JQUERY_URL     = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'