# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('kode_barang', models.CharField(max_length=200)),
                ('ukuran', models.CharField(choices=[('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=3)),
                ('nama', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('no_tlp', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('tanggal_order', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('no_resi', models.CharField(max_length=200)),
                ('lunas', models.BooleanField(default=False)),
                ('terkirim', models.BooleanField(default=False)),
            ],
        ),
    ]
