# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:36
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('gambar_kecil_1', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('gambar_kecil_2', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('gambar_kecil_3', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('kode', models.CharField(max_length=200, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.IntegerField()),
                ('ukuran_XXL', models.BooleanField(default=False)),
                ('ukuran_XL', models.BooleanField(default=False)),
                ('ukuran_LARGE', models.BooleanField(default=False)),
                ('ukuran_MEDIUM', models.BooleanField(default=False)),
                ('ukuran_SMALL', models.BooleanField(default=False)),
                ('warna', models.CharField(max_length=200)),
                ('sisa_stock', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan', ckeditor.fields.RichTextField()),
                ('ready_stock', models.BooleanField(default=False)),
                ('hot_product', models.BooleanField(default=False)),
                ('preorder', models.BooleanField(default=False)),
                ('low_stock', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('sale_percent', models.IntegerField(blank=True, null=True)),
                ('seo_description', models.TextField()),
                ('seo_keyword', models.CharField(max_length=200)),
                ('tanggal_publish', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.Product_Categories'),
        ),
    ]
