# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hot_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preorder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ready_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sisa_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ukuran_LARGE',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ukuran_MEDIUM',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ukuran_SMALL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ukuran_XL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ukuran_XXL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warna',
        ),
    ]
