# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_auto_20160728_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gambar_kecil_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_keyword',
        ),
    ]
